version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "thursday"
  - package-ecosystem: "maven"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "thursday"
